name: Bug report
description: You've found a bug with the Mairror API.
labels: ['type:bug', 'status:requirements', 'priority-5-triage']
body:
  - type: markdown
    attributes:
      value: |
        Before you begin to fill out the form, make sure you have actually found a bug.
        If you're not sure then create a [discussion](https://github.com/mairror/infrastructure/discussions) first.
        If you have questions or want help with Mairror infrastructure, then also create a [discussion](https://github.com/mairror/infrastructure/discussions).

  - type: dropdown
    id: how-are-you-running
    attributes:
      label: How are you running Mairror API?
      options:
        - 'Running without Docker'
        - 'Running using Docker'
        - 'Other'
    validations:
      required: true

  - type: dropdown
    id: what-component-is-causing-the-bug
    attributes:
      label: What component is causing the bug?
      options:
        - 'Python'
        - 'Dependencies'
        - 'FastAPI'
    validations:
      required: true

  - type: input
    id: commit-hash
    attributes:
      label: Tell us what is the commit hash you run.
    validations:
      required: false

  - type: dropdown
    id: regression-error
    attributes:
      label: Was this something which used to work for you, and then stopped?
      options:
        - 'It used to work, and then stopped'
        - 'I never saw this working'
    validations:
      required: true

  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: 'Do not report any security concerns here. Email organization members instead.'
    validations:
      required: true

  - type: textarea
    id: debug-logs
    attributes:
      label: Relevant debug logs
      description: |
        Try not to raise a bug report unless you've looked at the logs first.
        Paste the *relevant* logs here, not the entire thing and not just a link. to the dashboard (others do not have permissions to view them).
      value: |
        <details><summary>Logs</summary>

        ```
        Copy/paste any log here, between the starting and ending backticks
        ```

        </details>
    validations:
      required: false
